controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

admin_mobilhome_add:
    path: /admin/mobilhome/add
    controller: App\Controller\AdminMobilhomeController::addMobilhome